FROM node:18-alpine

ARG VERSION=latest

RUN apk add --no-cache --virtual buildtools build-base linux-headers udev python3

RUN mkdir /opt/flowforge-device
RUN npm install -g @flowfuse/device-agent@${VERSION}

EXPOSE 1880

LABEL org.label-schema.name="FlowFuse Device Agent" \
    org.label-schema.url="https://flowfuse.com" \
    org.label-schema.vcs-type="Git" \
    org.label-schema.vcs-url="https://github.com/FlowFuse/device-agent" \
    org.label-schema.docker.dockerfile="docker/Dockerfile" \
    org.schema-label.description="Collaborative, low code integration and automation environment" \
    authors="FlowFuse Inc."


CMD ["flowfuse-device-agent"]
