name: snapbuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - amd64
    steps:
    - uses: actions/checkout@v3
      with:
        path: snap
    - uses: docker/setup-qemu-action@v2
      with:
        platforms: ${{ matrix.platform }}
    - uses: diddlesnaps/snapcraft-multiarch-action@v1
      id: snapcraft
      with:
        architecture: ${{ matrix.platform }}
        path: snap